# Generated by Django 2.2.20 on 2021-06-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customtext_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='test',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
    ]
